import type { CollectionEntry } from "astro:content";

type ShapeToLabels<T extends Record<string, any>> = {
	[K in keyof T]: T[K] extends Record<string, any> ? ShapeToLabels<T[K]> : string | Record<string, string>;
};

export const labels: ShapeToLabels<CollectionEntry<"cars">["data"]> = {
	title: "Titel",
	image: "Billede",
	imageAlt: "Billedebeskrivelse",
	gallery: {
		image: "Billede",
		alt: "Beskrivelse",
	},
	videoTourUrl: "Video-tur URL",
	excerpt: "Beskrivelse",
	publishDate: "Oprettet" as unknown as ShapeToLabels<Date>,
	general: {
		make: "Bilmærke",
		model: "Model",
		variant: "Variant",
		type: "Type",
		price: "Kontantpris",
		salePrice: "Tilbudspris",
		newPrice: "Nypris",
		bodyType: "Karrosseri",
		drivetrain: "Trækhjul",
		doors: "Døre",
		seatingCapacity: "Sæder",
		condition: "Stand",
		availability: "Tilgængelighed",
		greenTax: "Grøn ejerafgift",
		firstRegistration: "1. registrering",
		octane: "Oktantal",
	},
	history: {
		mileage: "Kilometer kørt",
		year: "Modelår",
		previousOwners: "Tidligere ejere",
		accidentHistory: "Skadeshistorik",
	},
	technical: {
		horsePower: "Hestekræfter",
		torque: "Drejningsmoment",
		transmission: "Geartype",
		engineSizeCC: "Motorstørrelse",
		gears: "Antal gear",
		cilinders: "Cylindre",
		weight: "Vægt",
		topSpeed: "Tophastighed",
		zeroToHundred: "0–100 km/t",
		tankSize: "Tank",
	},
	efficiency: {
		fuelType: "Drivmiddel",
		fuelEfficiencyMPG: "Brændstoføkonomi (MPG)",
		fuelEfficiencyLPer100KM: "Forbrug (L/100 km)",
		fuelEfficiencyKMPerL: "Km/l",
		emissionsCO2: "CO₂-udledning",
		emissionsRating: "Emissionsklasse",
	},
	options: "Udstyr",
	security: {
		alarm: "Alarm",
		immobilizer: "Startspærre",
		airbags: "Airbags",
		abs: "ABS",
		esp: "ESP",
		tireCondition: "Dækstand",
		safetyRating: "Sikkerhedsklasse",
	},
	exterior: {
		color: "Farve",
		paintType: "Lakeringstype",
		wheelSize: "Fælgstørrelse",
		wheelType: "Fælgtype",
		height: "Højde",
		length: "Længde",
		width: "Bredde",
		loadCapacity: "Lasteevne",
	},
	interior: {
		materialSeats: "Sædemateriale",
		heatedSeats: "Sædevarme",
		ventilatedSeats: "Ventilerede sæder",
	},
	misc: {
		vin: "VIN",
		registrationStatus: "Registreringsstatus",
		warranty: "Garanti",
		dealerNotes: "Forhandlernoter",
		hidden: "Skjult",
		loanWidget: "Lånberegner",
		featured: "Fremhævet",
	},
};

export const categoryLabels = {
	general: "Specifikationer",
	history: "Historik",
	technical: "Teknik",
	exterior: "Eksteriør",
	interior: "Interiør",
	options: "Udstyrsliste",
	security: "Sikkerhed",
	efficiency: "Effektivitet",
	misc: "Diverse",
};
